### ISSUE TITLE
Delete darwinia.js package in github registry

### ISSUE THREAD

**Issue by clearloop** [darwinia-network/darwinia.js#3]
Delete npm package [@darwinia-network/darwinia.js][0]

1. no users
2. we use npm registry instead

## Reason...

Github packages are hard to use for now(most of us can not download successful even after a lot of config works), dup packages with npm will make users confused.

## Note

The darwinia.js package is deprecated, just sent a mail to github.

[0]: https://github.com/darwinia-network/darwinia.js/packages/180255

**Comment by HackFisher** [comment]
Refer

https://help.github.com/en/packages/publishing-and-managing-packages/deleting-a-package#about-public-package-deletion

I thinks keep packages synced in github registry is also acceptable and might be better, some users might more easy to get started if they was viewing github.

https://github.com/heikkipora/registry-sync

**Comment by clearloop** [comment]
> I think keep packages synced in github registry is also acceptable and might be better

The embarrassed part is that we use scope `@darwinia` in npm, but in github we use `@darwinia-network`, package names conflict, the easy sync way is using the same `@scope`.


And for scope name, I think the short one `@darwinia` is better than `@darwinia-network`...because it's easy to remember -> download + import.

**Comment by clearloop** [comment]
Just received the response of Github support, they said they don't support deleting packages...I'll re-open this issue when I figure out some better ideas.
